# Generated by Django 5.1.8 on 2025-05-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilog",
            name="status",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
