# Generated by Django 5.1.8 on 2025-05-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_apilog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilog",
            name="is_platform",
            field=models.BooleanField(default=False),
        ),
    ]
