# Generated by Django 5.1.8 on 2025-05-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_profile_image_url"),
        ("billing", "0003_apilog_is_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="organization",
            field=models.OneToOneField(
                default="da9b7f09-5412-4bfc-a3cb-0ff923c5619c",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to="accounts.organization",
            ),
            preserve_default=False,
        ),
    ]
