# Generated by Django 5.1.8 on 2025-05-10 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_wallet_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("api_charge", "API Charge")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(default="USD", max_length=5)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "INITIATED"),
                            (2, "SUCCESS"),
                            (3, "FAILED"),
                            (4, "CANCELLED"),
                        ]
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "payment_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("international", models.BooleanField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=20, null=True)),
                ("amount_refunded", models.IntegerField(blank=True, null=True)),
                (
                    "refund_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("captured", models.BooleanField(default=False)),
                ("fee", models.IntegerField(blank=True, null=True)),
                ("tax", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="billing.wallettransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
