# Generated by Django 5.1.8 on 2025-05-15 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_wallettransaction_transaction_type_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserPricing",
            new_name="UserAPIPricing",
        ),
    ]
