# Generated by Django 5.1.8 on 2025-05-15 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_profile_image_url"),
        ("billing", "0006_rename_userpricing_userapipricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "gateway",
                    models.CharField(choices=[("razorpay", "Razorpay")], max_length=20),
                ),
                ("description", models.TextField(blank=True)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("gateway_plan_id", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="Payment",
            new_name="APIPayment",
        ),
        migrations.RenameModel(
            old_name="PricingPlan",
            new_name="APIPlan",
        ),
        migrations.RenameModel(
            old_name="UserAPIPricing",
            new_name="APIUserPricing",
        ),
        migrations.RenameModel(
            old_name="Wallet",
            new_name="APIWallet",
        ),
        migrations.RenameModel(
            old_name="WalletTransaction",
            new_name="APIWalletTransaction",
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway_subscription_id",
                    models.CharField(max_length=100, unique=True),
                ),
                ("gateway_short_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authenticated", "Authenticated"),
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("halted", "Halted"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("charge_at", models.DateTimeField(blank=True, null=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("current_start", models.DateTimeField(blank=True, null=True)),
                ("current_end", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("remaining_count", models.PositiveIntegerField(default=0)),
                ("paid_count", models.PositiveIntegerField(default=0)),
                ("notes", models.JSONField(blank=True, default=dict)),
                ("has_scheduled_changes", models.BooleanField(default=False)),
                ("change_scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(default="USD", max_length=5)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "INITIATED"),
                            (2, "SUCCESS"),
                            (3, "FAILED"),
                            (4, "CANCELLED"),
                        ]
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "payment_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("international", models.BooleanField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=20, null=True)),
                ("amount_refunded", models.IntegerField(blank=True, null=True)),
                (
                    "refund_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("captured", models.BooleanField(default=False)),
                ("fee", models.IntegerField(blank=True, null=True)),
                ("tax", models.IntegerField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
