# Generated by Django 5.1.8 on 2025-05-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_remove_subscriptionwallet_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontokenallocation",
            name="source",
            field=models.CharField(
                choices=[
                    ("free_daily", "Free Daily Allocation"),
                    ("subscription_purchase", "Subscription Purchase"),
                    ("admin_grant", "Admin Grant"),
                ],
                max_length=50,
            ),
        ),
    ]
