# Generated by Django 5.1.8 on 2025-05-16 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_subscriptionpayment_plan_alter_subscription_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptiontokenallocation",
            name="subscription",
        ),
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(default="USD", max_length=5)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "INITIATED"),
                            (2, "SUCCESS"),
                            (3, "FAILED"),
                            (4, "CANCELLED"),
                        ]
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "payment_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "invoice_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("billing_start", models.DateTimeField(blank=True, null=True)),
                ("billing_end", models.DateTimeField(blank=True, null=True)),
                ("gateway_short_url", models.URLField(blank=True, null=True)),
                ("international", models.BooleanField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=20, null=True)),
                ("amount_refunded", models.IntegerField(blank=True, null=True)),
                (
                    "refund_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("captured", models.BooleanField(default=False)),
                ("fee", models.IntegerField(blank=True, null=True)),
                ("tax", models.IntegerField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="billing.subscriptionplan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="subscriptiontokenallocation",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.subscriptioninvoice",
            ),
        ),
        migrations.DeleteModel(
            name="SubscriptionPayment",
        ),
    ]
