# Generated by Django 5.1.8 on 2025-05-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_remove_subscriptiontokenallocation_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptioninvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issues"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("deleted", "Deleted"),
                ],
                max_length=20,
            ),
        ),
    ]
