# Generated by Django 5.1.8 on 2025-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_alter_subscriptioninvoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("authenticated", "Authenticated"),
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("halted", "Halted"),
                    ("paused", "Paused"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontokenallocation",
            name="expires_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
