# Generated by Django 5.1.8 on 2025-05-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_alter_subscription_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptioninvoice",
            name="captured",
        ),
    ]
