# Generated by Django 5.1.8 on 2025-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_remove_subscriptioninvoice_captured"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontokenallocation",
            name="is_deallocated",
            field=models.BooleanField(default=False),
        ),
    ]
