# Generated by Django 5.1.8 on 2025-05-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_subscriptiontokenallocation_is_deallocated"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilog",
            name="error_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionusagelog",
            name="error_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
