# Generated by Django 5.1.8 on 2025-04-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identity_provider_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
