# Generated by Django 5.1.8 on 2025-04-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_authtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="authtoken",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_token_set",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
