# Generated by Django 5.1.8 on 2025-04-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_authtoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="authtoken",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
