# Generated by Django 5.1.8 on 2025-04-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_organization_identity_provider_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
