# Generated by Django 5.1.8 on 2025-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_profile_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="domain",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_white_labeled",
            field=models.BooleanField(default=False),
        ),
    ]
