# Generated by Django 5.1.8 on 2025-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_organization_domain_organization_is_white_labeled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="domain",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
