# Generated by Django 5.1.8 on 2025-06-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_organization_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
