# Generated by Django 5.1.8 on 2025-06-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_organizationmembership_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="configuration",
            field=models.JSONField(default={}),
        ),
    ]
