# Generated by Django 5.1.8 on 2025-06-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_organization_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="configuration",
            field=models.JSONField(default=dict),
        ),
    ]
