# Generated by Django 5.1.8 on 2025-06-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_rename_configuration_organization_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="description",
        ),
    ]
