# Generated by Django 5.1.8 on 2025-04-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="config",
            field=models.JSONField(default=list),
        ),
    ]
