# Generated by Django 5.1.8 on 2025-04-13 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="title",
            new_name="name",
        ),
    ]
