# Generated by Django 5.1.8 on 2025-04-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_title_conversation_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_from_ai",
        ),
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("agent", "Agent"), ("system", "System")],
                default="system",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
