# Generated by Django 5.1.8 on 2025-04-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_message_is_from_ai_message_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="token_usage",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
