# Generated by Django 5.1.8 on 2025-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_message_token_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
