# Generated by Django 5.1.8 on 2025-04-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_conversationnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationnote",
            name="custom_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
