# Generated by Django 5.1.8 on 2025-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_conversationnote_custom_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="input_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="output_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
