# Generated by Django 5.1.8 on 2025-05-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_message_input_tokens_message_output_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="icon",
            field=models.CharField(default="abcd", max_length=255),
            preserve_default=False,
        ),
    ]
