# Generated by Django 5.1.8 on 2025-05-08 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_space_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="last_message_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2025, 5, 8, 10, 56, 23, 698508, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
