# Generated by Django 5.1.8 on 2025-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_conversation_last_message_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="description",
            field=models.TextField(),
        ),
    ]
