# Generated by Django 5.1.8 on 2025-05-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_space_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_created_via_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasource",
            name="is_created_via_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="space",
            name="is_created_via_platform",
            field=models.BooleanField(default=False),
        ),
    ]
