# Generated by Django 5.1.8 on 2025-05-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_conversation_is_created_via_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_upvote",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
