# Generated by Django 5.1.8 on 2025-05-15 12:02

import core.models.data_source
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_message_is_upvote_delete_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.models.data_source.user_directory_path,
            ),
        ),
    ]
