# Generated by Django 5.1.8 on 2025-05-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_datasource_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("indexed", "Indexed"),
                    ("errored", "Errored"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
