# Generated by Django 5.1.8 on 2025-05-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_datasource_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationnote",
            name="custom_type",
        ),
        migrations.AlterField(
            model_name="conversationnote",
            name="type",
            field=models.CharField(
                choices=[
                    ("summary", "Summary"),
                    ("insight", "Study Guide"),
                    ("action", "FAQs"),
                    ("bullet", "Bullet Points"),
                    ("note", "Note"),
                ],
                default="note",
                max_length=50,
            ),
        ),
    ]
