# Generated by Django 5.1.8 on 2025-06-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_conversationnote_custom_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="citation_type",
            field=models.CharField(
                choices=[("highlight", "Highlight"), ("inline", "Inline")],
                default="highlight",
                max_length=20,
            ),
        ),
    ]
