# Generated by Django 5.1.8 on 2025-06-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_tag_unique_together_alter_spacetag_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reasoning_type",
            field=models.CharField(
                choices=[("simple", "Simple"), ("complex", "Complex")],
                default="highlight",
                max_length=20,
            ),
        ),
    ]
