# Generated by Django 5.1.8 on 2025-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_message_reasoning_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reason_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
